name: Build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm ci

  release:
    name: Release
    needs: [build]
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Release GitHub Actions
        uses: technote-space/release-github-actions@v8
        with:
          BRANCH_NAME: releases/${MAJOR}
          CLEAN_TARGETS: '.gitignore,.github,*.lock,*.json'
          COMMIT_MESSAGE: 'Build: release ${{ github.ref_name }} via ${{ github.sha }}'

  test-release:
    name: Test release
    needs: [build]
    if: contains(github.ref, 'tags/test/v')
    runs-on: ubuntu-latest
    steps:
      - name: Release GitHub Actions
        uses: technote-space/release-github-actions@v6
        with:
          BRANCH_NAME: releases/${MAJOR}
          TEST_TAG_PREFIX: test/
          CLEAN_TARGETS: '.gitignore,.github,*.lock,*.json'
          COMMIT_MESSAGE: 'Build: release ${{ github.ref_name }} via ${{ github.sha }}'
